# Generated by Django 5.2.12 on 2026-03-20 06:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich_text", 0), ("html", 1), ("image", 5), ("blockquote", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "blockquote",
                                        "image",
                                    ],
                                    "label": "Rich Text",
                                },
                            ),
                            1: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {
                                    "help_text": "Paste raw HTML directly. Useful for migrating existing content or embedding custom markup.",
                                    "label": "Raw HTML",
                                },
                            ),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("full-width", "Full width"),
                                        ("left", "Left aligned"),
                                        ("right", "Right aligned"),
                                        ("w-50", "Half width"),
                                    ]
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 2), ("caption", 3), ("alignment", 4)]],
                                {
                                    "icon": "image",
                                    "label": "Image",
                                    "template": "underground_crm/blocks/image_block.html",
                                },
                            ),
                            6: ("wagtail.blocks.BlockQuoteBlock", (), {"label": "Blockquote"}),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Basic Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
