# Generated by Django 5.2.14 on 2026-06-13 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0004_alter_basicpage_body"),
        ("underground_crm", "0004_historicalperson"),
    ]

    operations = []
