# Generated by Django 5.2.15 on 2026-06-06 03:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('underground_crm', '0004_alter_basicpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('html', 1), ('image', 5), ('blockquote', 6), ('button', 11)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote', 'image'], 'label': 'Rich Text'}), 1: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Paste raw HTML directly. Useful for migrating existing content or embedding custom markup.', 'label': 'Raw HTML'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full-width', 'Full width'), ('left', 'Left aligned'), ('right', 'Right aligned'), ('w-50', 'Half width')]}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('alignment', 4)]], {'icon': 'image', 'label': 'Image', 'template': 'underground_crm/blocks/image_block.html'}), 6: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Blockquote'}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Button text'}), 8: ('underground_crm.blocks.PageURLBlock', (), {'label': 'Button URL'}), 9: ('underground_crm.blocks.ColorBlock', (), {'default': '#46d3e0', 'label': 'Background color', 'palette_only': False, 'palette_setting': 'UNDERGROUND_BUTTON_BACKGROUND_PALETTE'}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'Inherit (default)'), ('w-50', 'Half width'), ('w-100', 'Full width')], 'label': 'Width', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('text', 7), ('url', 8), ('background_color', 9), ('width', 10)]], {})}),
        ),
    ]
