# Generated by Django 5.2.14 on 2026-07-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0005_merge_0004_alter_basicpage_body_0004_historicalperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalperson",
            name="profile_picture_url",
            field=models.URLField(
                blank=True,
                help_text="Picture URL supplied by a social login provider, e.g. LinkedIn.",
                max_length=500,
                null=True,
                verbose_name="Profile picture URL",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="profile_picture_url",
            field=models.URLField(
                blank=True,
                help_text="Picture URL supplied by a social login provider, e.g. LinkedIn.",
                max_length=500,
                null=True,
                verbose_name="Profile picture URL",
            ),
        ),
    ]
