# Generated by Django 5.2.14 on 2026-07-06, then edited by hand: makemigrations
# was run from a theme project whose AppConfig extends BASIC_PAGE_BLOCKS at
# runtime, so it also emitted a spurious AlterField on basicpage.body that
# referenced theme block classes. That operation is omitted here — StreamField
# block changes do not alter the database schema, and this library's
# migrations must never depend on theme code.

import django.db.models.deletion
import underground_crm.models.pages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0005_persontag_was_authenticated"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventIndexPage",
            fields=[
                (
                    "basicpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="underground_crm.basicpage",
                    ),
                ),
                (
                    "page_size",
                    models.PositiveIntegerField(
                        default=10, help_text="Number of events to display per page."
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Index",
            },
            bases=(underground_crm.models.pages.FeedRoutedIndexMixin, "underground_crm.basicpage"),
        ),
    ]
