# Generated by Django 5.2.12 on 2026-03-26 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underground_crm', '0005_basicpage_og_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
