# Generated by Django 5.2.12 on 2026-04-24 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0006_basicpage_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="UndergroundBasicPage",
            fields=[
                (
                    "basicpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="underground_crm.basicpage",
                    ),
                ),
                (
                    "show_toc",
                    models.BooleanField(
                        default=False,
                        help_text="Show the table-of-contents sidebar for this page.",
                        verbose_name="Show table of contents",
                    ),
                ),
            ],
            options={
                "verbose_name": "Underground Basic Page",
            },
            bases=("underground_crm.basicpage",),
        ),
    ]
