# Generated by Django 5.2.14 on 2026-07-03 18:40

import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0006_historicalperson_profile_picture_url_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalperson",
            name="is_volunteer",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_volunteer",
        ),
        migrations.AddField(
            model_name="basicpage",
            name="og_type_override",
            field=models.CharField(
                blank=True,
                help_text="Override the 'og:type' meta value (see https://ogp.me/#types for valid values). Leave blank to use this page type's default.",
                max_length=50,
                null=True,
                verbose_name="Open Graph type override",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_protected",
            field=models.BooleanField(
                default=False,
                help_text="Ensures the tag can only be deleted by an admin through the console.",
                verbose_name="Is protected",
            ),
        ),
        migrations.CreateModel(
            name="FormPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "og_type_override",
                    models.CharField(
                        blank=True,
                        help_text="Override the 'og:type' meta value (see https://ogp.me/#types for valid values). Leave blank to use this page type's default.",
                        max_length=50,
                        null=True,
                        verbose_name="Open Graph type override",
                    ),
                ),
                (
                    "cache_ttl_override",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override the automatically calculated cache duration in seconds. Setting this to 0 will disable caching entirely. Leave blank to use the calculated value.",
                        null=True,
                        verbose_name="Cache TTL override (seconds)",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("rich_text", 0),
                            ("html", 1),
                            ("image", 5),
                            ("blockquote", 6),
                            ("button", 11),
                            ("checkbox", 12),
                            ("text", 13),
                            ("multiline_text", 14),
                            ("email", 15),
                            ("integer", 16),
                            ("decimal", 17),
                            ("float", 18),
                            ("url", 19),
                            ("date", 20),
                            ("time", 21),
                            ("datetime", 22),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "blockquote",
                                        "image",
                                    ],
                                    "label": "Rich Text",
                                },
                            ),
                            1: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {
                                    "help_text": "Paste raw HTML directly. Useful for migrating existing content or embedding custom markup.",
                                    "label": "Raw HTML",
                                },
                            ),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("full-width", "Full width"),
                                        ("left", "Left aligned"),
                                        ("right", "Right aligned"),
                                        ("w-50", "Half width"),
                                    ]
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 2), ("caption", 3), ("alignment", 4)]],
                                {
                                    "icon": "image",
                                    "label": "Image",
                                    "template": "underground_crm/blocks/image_block.html",
                                },
                            ),
                            6: ("wagtail.blocks.BlockQuoteBlock", (), {"label": "Blockquote"}),
                            7: ("wagtail.blocks.CharBlock", (), {"label": "Button text"}),
                            8: ("underground_crm.blocks.PageURLBlock", (), {"label": "Button URL"}),
                            9: (
                                "underground_crm.blocks.ColorBlock",
                                (),
                                {
                                    "default": "#46d3e0",
                                    "label": "Background color",
                                    "palette_only": False,
                                    "palette_setting": "UNDERGROUND_BUTTON_BACKGROUND_PALETTE",
                                },
                            ),
                            10: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("", "Inherit (default)"),
                                        ("w-50", "Half width"),
                                        ("w-100", "Full width"),
                                    ],
                                    "label": "Width",
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 7), ("url", 8), ("background_color", 9), ("width", 10)]],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "group": "Form inputs",
                                    "icon": "tick-inverse",
                                    "label": "Checkbox",
                                    "required": False,
                                    "template": "underground_crm/blocks/input_block.html",
                                },
                            ),
                            13: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "group": "Form inputs",
                                    "icon": "pilcrow",
                                    "label": "Text",
                                    "required": False,
                                    "template": "underground_crm/blocks/input_block.html",
                                },
                            ),
                            14: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "group": "Form inputs",
                                    "label": "Multi-line text",
                                    "required": False,
                                    "template": "underground_crm/blocks/input_block.html",
                                },
                            ),
                            15: (
                                "wagtail.blocks.EmailBlock",
                                (),
                                {
                                    "group": "Form inputs",
                                    "icon": "mail",
                                    "label": "Email",
                                    "required": False,
                                    "template": "underground_crm/blocks/input_block.html",
                                },
                            ),
                            16: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "group": "Form inputs",
                                    "label": "Integer",
                                    "required": False,
                                    "template": "underground_crm/blocks/input_block.html",
                                },
                            ),
                            17: (
                                "wagtail.blocks.DecimalBlock",
                                (),
                                {
                                    "group": "Form inputs",
                                    "label": "Decimal",
                                    "required": False,
                                    "template": "underground_crm/blocks/input_block.html",
                                },
                            ),
                            18: (
                                "wagtail.blocks.FloatBlock",
                                (),
                                {
                                    "group": "Form inputs",
                                    "label": "Float",
                                    "required": False,
                                    "template": "underground_crm/blocks/input_block.html",
                                },
                            ),
                            19: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "group": "Form inputs",
                                    "icon": "link",
                                    "label": "URL",
                                    "required": False,
                                    "template": "underground_crm/blocks/input_block.html",
                                },
                            ),
                            20: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {
                                    "group": "Form inputs",
                                    "icon": "date",
                                    "label": "Date",
                                    "required": False,
                                    "template": "underground_crm/blocks/input_block.html",
                                },
                            ),
                            21: (
                                "wagtail.blocks.TimeBlock",
                                (),
                                {
                                    "group": "Form inputs",
                                    "icon": "time",
                                    "label": "Time",
                                    "required": False,
                                    "template": "underground_crm/blocks/input_block.html",
                                },
                            ),
                            22: (
                                "wagtail.blocks.DateTimeBlock",
                                (),
                                {
                                    "group": "Form inputs",
                                    "icon": "date",
                                    "label": "Date and time",
                                    "required": False,
                                    "template": "underground_crm/blocks/input_block.html",
                                },
                            ),
                        },
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Search image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="FormPageTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_relations",
                        to="underground_crm.formpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="underground_crm.tag"
                    ),
                ),
            ],
            options={
                "unique_together": {("page", "tag")},
            },
        ),
        migrations.AddField(
            model_name="formpage",
            name="tags_to_apply",
            field=models.ManyToManyField(
                blank=True,
                help_text="Applied to the submitting Person's record. Authenticated submissions only.",
                related_name="form_pages",
                through="underground_crm.FormPageTag",
                to="underground_crm.tag",
                verbose_name="Tags to apply on submission",
            ),
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_authenticated", models.BooleanField(verbose_name="Is authenticated")),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        help_text="Only required for unauthenticated submissions.",
                        max_length=254,
                        null=True,
                        verbose_name="Email address",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Only recorded for unauthenticated submissions.",
                        null=True,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "language_preferences",
                    models.CharField(
                        blank=True,
                        help_text="Only recorded for unauthenticated submissions.",
                        max_length=128,
                        null=True,
                        verbose_name="Language preferences",
                    ),
                ),
                (
                    "submission_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Submission time"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="The page the visitor was on when they submitted this form.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_submissions",
                        to="wagtailcore.page",
                        verbose_name="Page",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only set for authenticated submissions.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form submission",
                "verbose_name_plural": "Form submissions",
                "ordering": ["-submission_time"],
            },
        ),
        migrations.CreateModel(
            name="SubmittedField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "block_id",
                    models.CharField(
                        help_text="UUID of the input block within the page body's StreamField.",
                        max_length=36,
                        verbose_name="Block ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='The input block\'s type name at submission time, e.g. "checkbox".',
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The label shown to the visitor at submission time.",
                        max_length=255,
                        verbose_name="Label",
                    ),
                ),
                ("has_value", models.BooleanField(verbose_name="Has value")),
                ("value", models.TextField(blank=True, default="", verbose_name="Value")),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_fields",
                        to="underground_crm.formsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submitted field",
                "verbose_name_plural": "Submitted fields",
                "unique_together": {("submission", "block_id")},
            },
        ),
    ]
