# Generated by Django 5.2.14 on 2026-07-03 18:41

from django.db import migrations

VOLUNTEER_TAG_NAME = "Volunteer"


def create_volunteer_tag(apps, schema_editor):
    Tag = apps.get_model("underground_crm", "Tag")
    Tag.objects.get_or_create(name=VOLUNTEER_TAG_NAME, defaults={"is_protected": True})


def delete_volunteer_tag(apps, schema_editor):
    Tag = apps.get_model("underground_crm", "Tag")
    Tag.objects.filter(name=VOLUNTEER_TAG_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0007_formpage_formsubmission_and_more"),
    ]

    operations = [
        # is_volunteer is replaced by tagging a Person with this Tag instead —
        # every Underground CRM install gets it, seeded protected so it can only
        # be deleted by an admin through the console (see Tag.is_protected and
        # the pre_delete signal in signals.py).
        migrations.RunPython(create_volunteer_tag, delete_volunteer_tag),
    ]
