# Generated by Django 5.2.14 on 2026-07-06, then edited by hand to remove a
# spurious AlterField on basicpage.body that referenced theme block classes
# (see the comment in 0006_event_index_page) and to clean up EventIndexPage's
# content type row.

import django.db.models.deletion
import modelcluster.fields
import uuid
from django.db import migrations, models


def delete_event_index_content_type(apps, schema_editor):
    """EventIndexPage only ever existed on this development branch (it was
    never part of a release, so no deployment holds pages of this type);
    without this its content type row would linger as a stale entry."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="underground_crm", model="eventindexpage").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("underground_crm", "0007_rename_blog_feed_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedpage",
            options={"verbose_name": "Feed Page"},
        ),
        migrations.AddField(
            model_name="feedpage",
            name="ordering",
            field=models.CharField(
                choices=[
                    ("newest_first", "Newest first (blog)"),
                    ("soonest_first", "Soonest first, upcoming only (events)"),
                ],
                default="newest_first",
                help_text="Newest first lists items by publication date, like a blog. Soonest first lists only items dated in the future, like an events calendar.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedpage",
            name="page_size",
            field=models.PositiveIntegerField(
                default=10, help_text="Number of items to display per page."
            ),
        ),
        migrations.CreateModel(
            name="FeedSubscription",
            fields=[
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Shown beside each item — usually the other organization's name.",
                        max_length=255,
                        verbose_name="Source name",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The address of the RSS or Atom feed.",
                        max_length=2000,
                        verbose_name="Feed URL",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="underground_crm.feedpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "feed subscription",
                "verbose_name_plural": "feed subscriptions",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="EventIndexPage",
        ),
        migrations.RunPython(delete_event_index_content_type, migrations.RunPython.noop),
    ]
