# Generated by Django 5.2.13 on 2026-04-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0008_eventpage_eventguest"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="population",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="This is updated automatically. It is only defined as a field so we can migrate legacy events seamlessly",
                null=True,
            ),
        ),
    ]
