# Generated by Django 5.2.14 on 2026-07-03 18:41

from django.db import migrations

FILTER_NAME = "Is Volunteer"

# Matches Person records tagged "Volunteer" — see migration 0008, which seeds
# that Tag.
CRITERIA = {
    "logic": "AND",
    "rules": [{"field": "tags__name", "operator": "exact", "value": "Volunteer"}],
}


def create_is_volunteer_filter(apps, schema_editor):
    PeopleFilter = apps.get_model("underground_crm", "PeopleFilter")
    PeopleFilter.objects.get_or_create(
        name=FILTER_NAME,
        defaults={
            "description": 'People tagged "Volunteer".',
            "criteria": CRITERIA,
        },
    )


def delete_is_volunteer_filter(apps, schema_editor):
    PeopleFilter = apps.get_model("underground_crm", "PeopleFilter")
    PeopleFilter.objects.filter(name=FILTER_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0008_seed_volunteer_tag"),
    ]

    operations = [
        migrations.RunPython(create_is_volunteer_filter, delete_is_volunteer_filter),
    ]
