# Generated by Django 5.2.14 on 2026-07-12, then reduced by hand to the
# Address.gnaf_id addition alone: makemigrations also picked up unrelated
# model drift pending on this branch, which belongs in its own migration.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0008_feed_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="gnaf_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text=(
                    "The G-NAF Address Detail PID of the address Addressr "
                    "matched (e.g. GANSW705239062). Set whenever the address "
                    "was resolved through Addressr, whether from an "
                    "autocomplete selection or a background geocode."
                ),
                max_length=32,
                null=True,
                verbose_name="G-NAF ID",
            ),
        ),
    ]
