# Generated by Django 5.2.14 on 2026-07-03 19:13
#
# EventPage now extends FormPage instead of BasicPage, so an event's RSVP
# form is just ordinary "input" blocks in its body, and RSVPs are recorded
# as FormSubmissions like any other FormPage — EventGuest is retired in
# favour of that shared mechanism. Hand-written rather than autodetected:
# changing an MTI model's parent isn't expressible as a field alteration,
# and there is no real EventPage/EventGuest data anywhere to preserve
# (EventPage had no template and no RSVP flow before this change).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0009_seed_is_volunteer_filter"),
    ]

    operations = [
        migrations.DeleteModel(name="EventGuest"),
        migrations.DeleteModel(name="EventPage"),
        migrations.CreateModel(
            name="EventPage",
            fields=[
                (
                    "formpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="underground_crm.formpage",
                    ),
                ),
                ("start_time", models.DateTimeField(null=True)),
                ("end_time", models.DateTimeField(null=True)),
                (
                    "population",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="This is updated automatically. It is only defined as a field so we can migrate legacy events seamlessly.",
                        null=True,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="underground_crm.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("underground_crm.formpage",),
        ),
    ]
