# Generated by Django 5.2.14 on 2026-07-13 04:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0009_address_gnaf_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("html", 1),
                    ("image", 5),
                    ("blockquote", 6),
                    ("button", 11),
                    ("glowing_button", 12),
                    ("blob", 15),
                    ("climate_stripes", 16),
                    ("laptop_frame", 18),
                    ("email_subscription", 22),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                                "blockquote",
                                "image",
                            ],
                            "label": "Rich Text",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {
                            "help_text": "Paste raw HTML directly. Useful for migrating existing content or embedding custom markup.",
                            "label": "Raw HTML",
                        },
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("full-width", "Full width"),
                                ("left", "Left aligned"),
                                ("right", "Right aligned"),
                                ("w-50", "Half width"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3), ("alignment", 4)]],
                        {
                            "icon": "image",
                            "label": "Image",
                            "template": "underground_crm/blocks/image_block.html",
                        },
                    ),
                    6: ("wagtail.blocks.BlockQuoteBlock", (), {"label": "Blockquote"}),
                    7: ("wagtail.blocks.CharBlock", (), {"label": "Button text"}),
                    8: ("underground_crm.blocks.PageURLBlock", (), {"label": "Button URL"}),
                    9: (
                        "underground_crm.blocks.ColorBlock",
                        (),
                        {
                            "default": "#46d3e0",
                            "label": "Background color",
                            "palette_only": False,
                            "palette_setting": "UNDERGROUND_BUTTON_BACKGROUND_PALETTE",
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Inherit (default)"),
                                ("w-50", "Half width"),
                                ("w-100", "Full width"),
                            ],
                            "label": "Width",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("url", 8), ("background_color", 9), ("width", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("url", 8), ("background_color", 9)]],
                        {},
                    ),
                    13: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Image"}),
                    14: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Overlay a rocking gradient on the image.",
                            "label": "Wobble",
                            "required": False,
                        },
                    ),
                    15: ("wagtail.blocks.StructBlock", [[("image", 13), ("wobble", 14)]], {}),
                    16: ("fusion.blocks.ClimateStripesBlock", (), {}),
                    17: (
                        "underground_crm.blocks.PageURLBlock",
                        (),
                        {
                            "help_text": "e.g. https://fusionparty.space/video/online_highlights_400.webm",
                            "label": "Video URL",
                        },
                    ),
                    18: ("wagtail.blocks.StructBlock", [[("video_url", 17)]], {}),
                    19: (
                        "fusion.blocks.TagChooserBlock",
                        (),
                        {
                            "help_text": "Applied to the submitting Person's record; visitors already carrying it see the acknowledgement instead of the form.",
                            "label": "Tag to apply",
                        },
                    ),
                    20: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 0), ("image", 5), ("blockquote", 6), ("button", 11)]],
                        {
                            "help_text": "Shown to visitors who already carry the tag. Leave empty for the built-in thank-you message.",
                            "label": "Acknowledgement",
                            "required": False,
                        },
                    ),
                    21: (
                        "underground_crm.blocks.PageURLBlock",
                        (),
                        {
                            "help_text": "Where the unsubscribe link points. Leave blank to hide the link.",
                            "label": "Unsubscribe URL",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("tag_to_apply", 19), ("acknowledgement", 20), ("unsubscribe_url", 21)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="First name (for the electoral roll)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="First name (for the electoral roll)",
                max_length=100,
                null=True,
            ),
        ),
    ]
