# Generated by Django 5.2.14 on 2026-07-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0009_address_gnaf_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperson",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="First name (for the electoral roll)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="First name (for the electoral roll)",
                max_length=100,
                null=True,
            ),
        ),
    ]
