# Generated by Django 5.2.13 on 2026-04-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0010_blog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="undergroundbasicpage",
            options={"verbose_name": "Basic Page"},
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="country_code",
            field=models.CharField(db_index=True, default="AU", max_length=2),
        ),
        migrations.AlterField(
            model_name="address",
            name="line1",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="address",
            name="line2",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="address",
            name="postcode",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
