# Generated by Django 5.2.14 on 2026-07-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0010_eventpage_extends_formpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedfield",
            name="value",
            field=models.TextField(blank=True, default="", verbose_name="Value"),
        ),
    ]
