# Generated by Django 5.2.13 on 2026-04-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0011_alter_undergroundbasicpage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicpage",
            name="legacy_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
