# Generated by Django 5.2.14 on 2026-07-03 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0011_submittedfield_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventGuest",
            fields=[
                (
                    "formsubmission_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="underground_crm.formsubmission",
                    ),
                ),
                (
                    "extra_guests",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many guests will be accompanying you?",
                        verbose_name="Extra guests",
                    ),
                ),
            ],
            bases=("underground_crm.formsubmission",),
        ),
        migrations.AlterField(
            model_name="inputfield",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to auto-generate from the English description, or specify one explicitly to override it.",
                max_length=200,
                unique=True,
                verbose_name="Name",
            ),
        ),
    ]
