# Generated by Django 5.2.14 on 2026-07-13 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0011_fix_blogpost_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationpage",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                help_text="Granted to the registering Person on submission, unless they already hold one of this type (active or not).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration_pages",
                to="underground_crm.membershiptype",
                verbose_name="Membership",
            ),
        ),
    ]
