# Generated by Django 5.2.14 on 2026-07-13 12:07

import underground_crm.blocks
import underground_crm.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0012_registrationpage_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicpage",
            name="body",
            field=underground_crm.fields.DeclaredBlocksStreamField(
                [("rich_text", 0), ("html", 1), ("image", 5), ("blockquote", 6), ("button", 11)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                                "blockquote",
                                "image",
                            ],
                            "label": "Rich Text",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {
                            "help_text": "Paste raw HTML directly. Useful for migrating existing content or embedding custom markup.",
                            "label": "Raw HTML",
                        },
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("full-width", "Full width"),
                                ("left", "Left aligned"),
                                ("right", "Right aligned"),
                                ("w-50", "Half width"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3), ("alignment", 4)]],
                        {
                            "icon": "image",
                            "label": "Image",
                            "template": "underground_crm/blocks/image_block.html",
                        },
                    ),
                    6: ("wagtail.blocks.BlockQuoteBlock", (), {"label": "Blockquote"}),
                    7: ("wagtail.blocks.CharBlock", (), {"label": "Button text"}),
                    8: ("underground_crm.blocks.PageURLBlock", (), {"label": "Button URL"}),
                    9: (
                        "underground_crm.blocks.ColorBlock",
                        (),
                        {
                            "default": "#46d3e0",
                            "label": "Background color",
                            "palette_only": False,
                            "palette_setting": "UNDERGROUND_BUTTON_BACKGROUND_PALETTE",
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Inherit (default)"),
                                ("w-50", "Half width"),
                                ("w-100", "Full width"),
                            ],
                            "label": "Width",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("url", 8), ("background_color", 9), ("width", 10)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="formpage",
            name="body",
            field=underground_crm.fields.DeclaredBlocksStreamField(
                [
                    ("rich_text", 0),
                    ("html", 1),
                    ("image", 5),
                    ("blockquote", 6),
                    ("button", 11),
                    ("checkbox", 12),
                    ("text", 13),
                    ("multiline_text", 14),
                    ("email", 15),
                    ("address", 16),
                    ("integer", 17),
                    ("decimal", 18),
                    ("float", 19),
                    ("url", 20),
                    ("date", 21),
                    ("time", 22),
                    ("datetime", 23),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                                "blockquote",
                                "image",
                            ],
                            "label": "Rich Text",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {
                            "help_text": "Paste raw HTML directly. Useful for migrating existing content or embedding custom markup.",
                            "label": "Raw HTML",
                        },
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("full-width", "Full width"),
                                ("left", "Left aligned"),
                                ("right", "Right aligned"),
                                ("w-50", "Half width"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3), ("alignment", 4)]],
                        {
                            "icon": "image",
                            "label": "Image",
                            "template": "underground_crm/blocks/image_block.html",
                        },
                    ),
                    6: ("wagtail.blocks.BlockQuoteBlock", (), {"label": "Blockquote"}),
                    7: ("wagtail.blocks.CharBlock", (), {"label": "Button text"}),
                    8: ("underground_crm.blocks.PageURLBlock", (), {"label": "Button URL"}),
                    9: (
                        "underground_crm.blocks.ColorBlock",
                        (),
                        {
                            "default": "#46d3e0",
                            "label": "Background color",
                            "palette_only": False,
                            "palette_setting": "UNDERGROUND_BUTTON_BACKGROUND_PALETTE",
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Inherit (default)"),
                                ("w-50", "Half width"),
                                ("w-100", "Full width"),
                            ],
                            "label": "Width",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("url", 8), ("background_color", 9), ("width", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "group": "Form inputs",
                            "icon": "tick-inverse",
                            "label": "Checkbox",
                            "required": False,
                            "template": "underground_crm/blocks/input_block.html",
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "group": "Form inputs",
                            "icon": "pilcrow",
                            "label": "Text",
                            "required": False,
                            "template": "underground_crm/blocks/input_block.html",
                        },
                    ),
                    14: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "group": "Form inputs",
                            "label": "Multi-line text",
                            "required": False,
                            "template": "underground_crm/blocks/input_block.html",
                        },
                    ),
                    15: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {
                            "group": "Form inputs",
                            "icon": "mail",
                            "label": "Email",
                            "required": False,
                            "template": "underground_crm/blocks/input_block.html",
                        },
                    ),
                    16: (
                        "underground_crm.blocks.AddressBlock",
                        (),
                        {
                            "group": "Form inputs",
                            "icon": "site",
                            "label": "Address",
                            "required": False,
                            "template": "underground_crm/blocks/input_block.html",
                        },
                    ),
                    17: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "group": "Form inputs",
                            "label": "Integer",
                            "required": False,
                            "template": "underground_crm/blocks/input_block.html",
                        },
                    ),
                    18: (
                        "wagtail.blocks.DecimalBlock",
                        (),
                        {
                            "group": "Form inputs",
                            "label": "Decimal",
                            "required": False,
                            "template": "underground_crm/blocks/input_block.html",
                        },
                    ),
                    19: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "group": "Form inputs",
                            "label": "Float",
                            "required": False,
                            "template": "underground_crm/blocks/input_block.html",
                        },
                    ),
                    20: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "group": "Form inputs",
                            "icon": "link",
                            "label": "URL",
                            "required": False,
                            "template": "underground_crm/blocks/input_block.html",
                        },
                    ),
                    21: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "group": "Form inputs",
                            "icon": "date",
                            "label": "Date",
                            "required": False,
                            "template": "underground_crm/blocks/input_block.html",
                        },
                    ),
                    22: (
                        "wagtail.blocks.TimeBlock",
                        (),
                        {
                            "group": "Form inputs",
                            "icon": "time",
                            "label": "Time",
                            "required": False,
                            "template": "underground_crm/blocks/input_block.html",
                        },
                    ),
                    23: (
                        "wagtail.blocks.DateTimeBlock",
                        (),
                        {
                            "group": "Form inputs",
                            "icon": "date",
                            "label": "Date and time",
                            "required": False,
                            "template": "underground_crm/blocks/input_block.html",
                        },
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="registrationpage",
            name="body",
            field=underground_crm.fields.DeclaredBlocksStreamField(
                [
                    ("rich_text", 0),
                    ("html", 1),
                    ("image", 5),
                    ("blockquote", 6),
                    ("button", 11),
                    ("person_field", 14),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                                "blockquote",
                                "image",
                            ],
                            "label": "Rich Text",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {
                            "help_text": "Paste raw HTML directly. Useful for migrating existing content or embedding custom markup.",
                            "label": "Raw HTML",
                        },
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("full-width", "Full width"),
                                ("left", "Left aligned"),
                                ("right", "Right aligned"),
                                ("w-50", "Half width"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3), ("alignment", 4)]],
                        {
                            "icon": "image",
                            "label": "Image",
                            "template": "underground_crm/blocks/image_block.html",
                        },
                    ),
                    6: ("wagtail.blocks.BlockQuoteBlock", (), {"label": "Blockquote"}),
                    7: ("wagtail.blocks.CharBlock", (), {"label": "Button text"}),
                    8: ("underground_crm.blocks.PageURLBlock", (), {"label": "Button URL"}),
                    9: (
                        "underground_crm.blocks.ColorBlock",
                        (),
                        {
                            "default": "#46d3e0",
                            "label": "Background color",
                            "palette_only": False,
                            "palette_setting": "UNDERGROUND_BUTTON_BACKGROUND_PALETTE",
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Inherit (default)"),
                                ("w-50", "Half width"),
                                ("w-100", "Full width"),
                            ],
                            "label": "Width",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("url", 8), ("background_color", 9), ("width", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": underground_crm.blocks.registration_person_field_choices,
                            "help_text": "Which detail of the visitor's record this input reads and updates.",
                            "label": "Person field",
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Shown to the visitor instead of the field's default label.",
                            "label": "Label override",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("field", 12), ("label_override", 13)]],
                        {},
                    ),
                },
                default=underground_crm.blocks.default_registration_body,
            ),
        ),
    ]
