# Generated by Django 5.2.14 on 2026-09-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0013_alter_basicpage_body_alter_formpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperson",
            name="prefix",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Name prefix"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="prefix",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Name prefix"
            ),
        ),
    ]
