# Generated by Django 5.2.14 on 2026-09-11 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0014_alter_historicalperson_prefix_alter_person_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperson",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, verbose_name="Created at"
            ),
        ),
    ]
