# Generated by Django 5.2.13 on 2026-04-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0014_personfilter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personfilter",
            name="criteria",
            field=models.JSONField(
                default=dict, help_text="Nested AND/OR rule tree built with the query builder."
            ),
        ),
    ]
