# Generated by Django 5.2.14 on 2026-09-16 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0015_person_created_at_defaults_to_now"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "person",
                "verbose_name_plural": "people",
            },
        ),
    ]
