# Generated by Django 5.2.14 on 2026-09-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0016_alter_person_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedpage",
            name="show_slug_as_breadcrumb",
            field=models.BooleanField(
                default=False,
                help_text="If disabled (the default), this feed's items are addressed directly beneath this page's own parent, so an item's URL omits this feed's slug — the way the legacy CMS addresses blog and calendar entries. If enabled, item URLs are nested beneath this page's own URL as usual.",
                verbose_name="Show slug as breadcrumb",
            ),
        ),
    ]
