# Generated by Django 5.2.13 on 2026-04-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0017_remove_urlredirection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personnote",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "note",
                "verbose_name_plural": "notes",
            },
        ),
        migrations.AlterModelOptions(
            name="persontag",
            options={"verbose_name": "tag", "verbose_name_plural": "tags"},
        ),
        migrations.AddField(
            model_name="peoplefilter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
