# Generated by Django 5.2.14 on 2026-10-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0019_alter_basicpage_body_alter_blogpost_intro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperson",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="First name (as per the electoral roll)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Last name / family name"
            ),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="preferred_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Preferred name / first name"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="First name (as per the electoral roll)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Last name / family name"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="preferred_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Preferred name / first name"
            ),
        ),
    ]
