# Generated by Django 5.2.14 on 2026-10-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0020_alter_historicalperson_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperson",
            name="first_name",
            field=models.CharField(
                blank=True, help_text="As per the electoral roll", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Family name",
                max_length=100,
                null=True,
                verbose_name="Last name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="preferred_name",
            field=models.CharField(
                blank=True,
                help_text="First name / nickname",
                max_length=100,
                null=True,
                verbose_name="Preferred name",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(
                blank=True, help_text="As per the electoral roll", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Family name",
                max_length=100,
                null=True,
                verbose_name="Last name",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="preferred_name",
            field=models.CharField(
                blank=True,
                help_text="First name / nickname",
                max_length=100,
                null=True,
                verbose_name="Preferred name",
            ),
        ),
    ]
