# Generated by Django 5.2.13 on 2026-05-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0020_merge"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="has_html_permission",
            field=models.BooleanField(
                default=False,
                help_text="Does this user have permission to create raw HTML for web pages?",
            ),
        ),
    ]
