# Generated by Django 5.2.13 on 2026-05-01 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0021_add_has_html_permission_to_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="geocode_confidence",
        ),
    ]
