# Generated by Django 5.2.13 on 2026-05-03 00:46
# Manually amended: the auto-generated through tables already exist in the database
# with bigint IDENTITY PKs.  We:
#   1. Drop the IDENTITY constraint and ALTER the id column to uuid (database only).
#   2. Register explicit PersonGroup / PersonPermission through models in the migration
#      state so Django's ORM knows about them (state only; no table CREATE).
#   3. Update the Person.groups / Person.user_permissions field definitions in state
#      to reference the new through models (state only; AlterField cannot change
#      through=, so we use RemoveField + AddField instead).

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def drop_identity_and_convert_to_uuid_groups(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE underground_crm_person_groups "
            "    ALTER COLUMN id DROP IDENTITY IF EXISTS;"
        )
        cursor.execute(
            "ALTER TABLE underground_crm_person_groups "
            "    ALTER COLUMN id TYPE uuid USING gen_random_uuid();"
        )


def drop_identity_and_convert_to_uuid_permissions(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE underground_crm_person_user_permissions "
            "    ALTER COLUMN id DROP IDENTITY IF EXISTS;"
        )
        cursor.execute(
            "ALTER TABLE underground_crm_person_user_permissions "
            "    ALTER COLUMN id TYPE uuid USING gen_random_uuid();"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("underground_crm", "0022_remove_address_geocode_confidence"),
    ]

    operations = [
        # ── PersonGroup ──────────────────────────────────────────────────────────
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="PersonGroup",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "group",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                            ),
                        ),
                        (
                            "person",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "underground_crm_person_groups",
                        "unique_together": {("person", "group")},
                    },
                ),
            ],
            database_operations=[
                # Drop the bigint IDENTITY constraint, then widen the column to uuid.
                # gen_random_uuid() assigns a fresh UUID to every existing row.
                migrations.RunPython(
                    drop_identity_and_convert_to_uuid_groups,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
        # Swap the Person.groups M2M to point at the new explicit through model.
        # AlterField cannot change through=, so we remove and re-add the field in state only.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name="person", name="groups"),
                migrations.AddField(
                    model_name="person",
                    name="groups",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text=(
                            "The groups this user belongs to. A user will get all permissions "
                            "granted to each of their groups."
                        ),
                        related_name="user_set",
                        related_query_name="user",
                        through="underground_crm.PersonGroup",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            database_operations=[],
        ),
        # ── PersonPermission ─────────────────────────────────────────────────────
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="PersonPermission",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "permission",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, to="auth.permission"
                            ),
                        ),
                        (
                            "person",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "underground_crm_person_user_permissions",
                        "unique_together": {("person", "permission")},
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    drop_identity_and_convert_to_uuid_permissions,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name="person", name="user_permissions"),
                migrations.AddField(
                    model_name="person",
                    name="user_permissions",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        through="underground_crm.PersonPermission",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
