# Generated by Django 5.2.13 on 2026-05-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0023_persongroup_alter_person_groups_personpermission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engagement",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("signup", "Signed up"),
                    ("donated", "Donated"),
                    ("petitioned", "Signed petition"),
                    ("rsvp", "RSVP'd to event"),
                    ("attended_event", "Attended event"),
                    ("volunteered", "Volunteered"),
                    ("contacted", "Contacted by staff"),
                    ("email_opened", "Opened email"),
                    ("email_clicked", "Clicked link in email"),
                    ("followed_page", "Followed page"),
                    ("survey_responded", "Responded to survey"),
                    ("membership_joined", "Joined as member"),
                    ("membership_renewed", "Renewed membership"),
                    ("unsubscribed", "Unsubscribed"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
