# Generated by Django 5.2.13 on 2026-05-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0024_alter_engagement_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive users are treated as tombstones",
                verbose_name="Is active",
            ),
        ),
    ]
