# Generated by Django 5.2.14 on 2026-05-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0025_alter_person_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="email_is_bad",
            field=models.BooleanField(
                blank=True, help_text="Can the user actually be emailed?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="unsubscribed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the person unsubscribed from all emails.", null=True
            ),
        ),
    ]
