# Generated by Django 5.2.14 on 2026-05-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0027_alter_address_city_alter_address_line1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="facebook_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="membership_number",
            field=models.CharField(
                blank=True,
                help_text="Membership number from a previous membership system.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="submitted_address",
            field=models.TextField(
                blank=True,
                help_text="Raw address string as submitted by the person, before geocoding.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="twitter_login",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
