# Generated by Django 5.2.14 on 2026-07-05 09:43

import django.db.models.deletion
import underground_email.models
import uuid
import wagtail.fields
import wagtail.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("underground_crm", "0003_seed_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplatedGreeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "greeting",
                    models.CharField(
                        help_text="Use {{ first_name }}, {{ last_name }}, or {{ full_name }}, along with a greeting. This will be included in every email.",
                        max_length=255,
                        verbose_name="greeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "templated greeting",
                "verbose_name_plural": "templated greetings",
            },
        ),
        migrations.CreateModel(
            name="EmailSender",
            fields=[
                (
                    "sender",
                    models.OneToOneField(
                        help_text="Emails will be sent from this user's email address. This assumes the domain has been registered with SMTP2Go",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Attributed sender",
                    ),
                ),
                (
                    "signature",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="This editing view looks slightly different to the final version",
                        verbose_name="Signature",
                    ),
                ),
                (
                    "sending_permission_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who can send emails attributed to this identity?",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                        verbose_name="Sending permission group",
                    ),
                ),
            ],
            options={
                "verbose_name": "email sender",
                "verbose_name_plural": "email senders",
            },
        ),
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "utm_id",
                    models.CharField(
                        default=underground_email.models.generate_base64_id,
                        help_text="A unique identifier for the Urchin Traffic Module to track conversions",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UTM identifier",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="The campaign's subject line, as you'd like it to be seen by the public",
                        max_length=255,
                        verbose_name="subject",
                    ),
                ),
                (
                    "preview_text",
                    models.CharField(
                        blank=True,
                        help_text="Short summary shown by email clients after the subject line",
                        max_length=255,
                        null=True,
                        verbose_name="preview text",
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        help_text="The Django template used to render this email",
                        max_length=200,
                        verbose_name="template",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich_text", 0), ("button", 5), ("hrule", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "blockquote",
                                        "image",
                                    ],
                                    "label": "Rich text",
                                },
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Button text"}),
                            2: ("wagtail.blocks.URLBlock", (), {"label": "Button URL"}),
                            3: (
                                "underground_crm.blocks.ColorBlock",
                                (),
                                {
                                    "default": "#77ff33",
                                    "label": "Background color",
                                    "palette_only": False,
                                },
                            ),
                            4: (
                                "underground_crm.blocks.ColorBlock",
                                (),
                                {
                                    "default": "#ffffff",
                                    "label": "Text color",
                                    "palette_only": False,
                                    "palette_setting": "UNDERGROUND_EMAIL_BUTTON_TEXT_COLORS",
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 1), ("url", 2), ("background_color", 3), ("color", 4)]],
                                {},
                            ),
                            6: (
                                "underground_crm.blocks.ColorBlock",
                                (),
                                {
                                    "default": "#cccccc",
                                    "label": "Color",
                                    "palette_only": False,
                                    "palette_setting": "UNDERGROUND_EMAIL_HRULE_COLORS",
                                },
                            ),
                            7: ("wagtail.blocks.StructBlock", [[("color", 6)]], {}),
                        },
                    ),
                ),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Draft"), (1, "Scheduled"), (2, "Sent")],
                        default=0,
                        help_text="To actually send the email campaign, please run the action from the previous menu",
                    ),
                ),
                (
                    "sending_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave this blank to send immediately",
                        null=True,
                        verbose_name="sending date",
                    ),
                ),
                (
                    "sent_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="sent count"),
                ),
                (
                    "clicked_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="A count of how many users clicked links from this email",
                        null=True,
                        verbose_name="clicked count",
                    ),
                ),
                (
                    "opened_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Google and Apple have measures preventing us from measuring this, so it should not be trusted",
                        null=True,
                        verbose_name="opened count",
                    ),
                ),
                (
                    "spam_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="A count of how many recipients marked this as spam or rejected the message",
                        null=True,
                        verbose_name="spam count",
                    ),
                ),
                (
                    "unsubscription_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="unsubscription count"
                    ),
                ),
                (
                    "smtp2go_template_id",
                    models.CharField(blank=True, max_length=50, verbose_name="smtp2go template ID"),
                ),
                (
                    "people_filter",
                    models.ForeignKey(
                        blank=True,
                        help_text="This must be specified before sending",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="underground_crm.peoplefilter",
                        verbose_name="people filter",
                    ),
                ),
                (
                    "unsubscription_tag",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which tag should be removed if the recipient clicks to unsubscribe? If not set, such recipients will be converted to tombstones (losing their membership).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="underground_crm.tag",
                        verbose_name="Unsubscription tag",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="underground_email.emailsender",
                        verbose_name="sender",
                    ),
                ),
                (
                    "greeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="underground_email.templatedgreeting",
                        verbose_name="greeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "email campaign",
                "verbose_name_plural": "email campaigns",
            },
            bases=(wagtail.models.PreviewableMixin, models.Model),
        ),
    ]
