# Generated by Django 5.2.13 on 2026-05-03 00:13

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("underground_email", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsender",
            name="sender",
            field=models.OneToOneField(
                help_text="Emails will be attributed to this user, but might not actually be sent from their email address",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Attributed sender",
            ),
        ),
        migrations.AlterField(
            model_name="emailsender",
            name="sending_permission_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Who can send emails attributed to this identity?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
                verbose_name="Sending permission group",
            ),
        ),
        migrations.AlterField(
            model_name="emailsender",
            name="signature",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Signature"),
        ),
    ]
