# Generated by Django 5.2.13 on 2026-05-04 00:37

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_email", "0002_alter_emailsender_sender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="state",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Draft"), (1, "Scheduled"), (2, "Sent")],
                default=0,
                help_text="To send the email campaign, please run the action from the previous menu",
            ),
        ),
        migrations.AlterField(
            model_name="emailsender",
            name="signature",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="This editing view looks slightly different to the final version",
                verbose_name="Signature",
            ),
        ),
    ]
