# Generated by Django 5.2.14 on 2026-10-02 03:35

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_email", "0004_alter_emailcampaign_body"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("button", 5), ("hrule", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                                "blockquote",
                                "image",
                            ],
                            "label": "Rich text",
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Button text"}),
                    2: ("wagtail.blocks.URLBlock", (), {"label": "Button URL"}),
                    3: (
                        "underground_crm.blocks.ColorBlock",
                        (),
                        {"default": "#77ff33", "label": "Background color", "palette_only": False},
                    ),
                    4: (
                        "underground_crm.blocks.ColorBlock",
                        (),
                        {
                            "default": "#ffffff",
                            "label": "Text color",
                            "palette_only": False,
                            "palette_setting": "UNDERGROUND_EMAIL_BUTTON_TEXT_COLORS",
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("url", 2), ("background_color", 3), ("color", 4)]],
                        {},
                    ),
                    6: (
                        "underground_crm.blocks.ColorBlock",
                        (),
                        {
                            "default": "#cccccc",
                            "label": "Color",
                            "palette_only": False,
                            "palette_setting": "UNDERGROUND_EMAIL_HRULE_COLORS",
                        },
                    ),
                    7: ("wagtail.blocks.StructBlock", [[("color", 6)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="emailsender",
            name="sender",
            field=models.OneToOneField(
                help_text="Emails will be sent from this user's email address. This assumes the domain has been registered with SMTP2Go. Choose someone who is a staff member or who has an email address at one of the domains specified in DJANGO_ALLOWED_HOSTS.",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Attributed sender",
            ),
        ),
    ]
