# Generated by Django 5.2.13 on 2026-05-04 04:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("underground_email", "0005_alter_emailcampaign_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("button", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                                "blockquote",
                                "image",
                            ],
                            "label": "Rich text",
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Button text"}),
                    2: ("wagtail.blocks.URLBlock", (), {"label": "Button URL"}),
                    3: (
                        "underground_email.blocks.ColorBlock",
                        (),
                        {"default": "#ff7fff", "label": "Background color", "palette_only": False},
                    ),
                    4: (
                        "underground_email.blocks.ColorBlock",
                        (),
                        {"default": "#ffffff", "label": "Text color", "palette_only": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("url", 2), ("background_color", 3), ("color", 4)]],
                        {},
                    ),
                },
            ),
        ),
    ]
