# Generated by Django 5.2.14 on 2026-10-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_email", "0005_alter_emailcampaign_body_alter_emailsender_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatedgreeting",
            name="greeting",
            field=models.CharField(
                help_text="Use {{ first_name }}, {{ preferred_or_first_name }}, {{ last_name }}, or {{ full_name }}, along with a greeting. This will be included in every email.",
                max_length=255,
                verbose_name="greeting",
            ),
        ),
    ]
