# Generated by Django 5.2.13 on 2026-05-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_email", "0007_alter_emailcampaign_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcampaign",
            name="preview_text",
            field=models.CharField(
                blank=True,
                help_text="Short summary shown by email clients after the subject line",
                max_length=255,
                verbose_name="preview text",
            ),
        ),
    ]
