# Generated by Django 5.2.13 on 2026-05-04 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_email", "0009_emailcampaign_unsubscription_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="sending_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Leave this blank to send immediately",
                null=True,
                verbose_name="sending date",
            ),
        ),
        migrations.AlterField(
            model_name="emailcampaign",
            name="state",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Draft"), (1, "Scheduled"), (2, "Sent")],
                default=0,
                help_text="To actually send the email campaign, please run the action from the previous menu",
            ),
        ),
        migrations.AlterField(
            model_name="emailsender",
            name="sender",
            field=models.OneToOneField(
                help_text="Emails will be sent from this user's email address. This assumes the domain has been registered with SMTP2Go",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Attributed sender",
            ),
        ),
    ]
