# Generated by Django 5.2.14 on 2026-05-17 23:22

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_email", "0010_alter_emailcampaign_sending_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("button", 5), ("hrule", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                                "blockquote",
                                "image",
                            ],
                            "label": "Rich text",
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Button text"}),
                    2: ("wagtail.blocks.URLBlock", (), {"label": "Button URL"}),
                    3: (
                        "underground_email.blocks.ColorBlock",
                        (),
                        {"default": "#ff7fff", "label": "Background color", "palette_only": False},
                    ),
                    4: (
                        "underground_email.blocks.ColorBlock",
                        (),
                        {
                            "default": "#ffffff",
                            "label": "Text color",
                            "palette_only": False,
                            "palette_setting": "UNDERGROUND_EMAIL_BUTTON_TEXT_COLORS",
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("url", 2), ("background_color", 3), ("color", 4)]],
                        {},
                    ),
                    6: (
                        "underground_email.blocks.ColorBlock",
                        (),
                        {
                            "default": "#e8e0ff",
                            "label": "Color",
                            "palette_only": False,
                            "palette_setting": "UNDERGROUND_EMAIL_HRULE_COLORS",
                        },
                    ),
                    7: ("wagtail.blocks.StructBlock", [[("color", 6)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="emailcampaign",
            name="opened_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Google and Apple have measures preventing us from measuring this, so it should not be trusted",
                null=True,
                verbose_name="opened count",
            ),
        ),
        migrations.AlterField(
            model_name="emailcampaign",
            name="preview_text",
            field=models.CharField(
                blank=True,
                help_text="Short summary shown by email clients after the subject line",
                max_length=255,
                null=True,
                verbose_name="preview text",
            ),
        ),
    ]
