# Generated by Django 5.2.14 on 2026-06-01 03:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('underground_email', '0011_alter_emailcampaign_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('button', 5), ('hrule', 7)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote', 'image'], 'label': 'Rich text'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Button text'}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Button URL'}), 3: ('underground_email.blocks.ColorBlock', (), {'default': '#000000', 'label': 'Background color', 'palette_only': False}), 4: ('underground_email.blocks.ColorBlock', (), {'default': '#ffffff', 'label': 'Text color', 'palette_only': False, 'palette_setting': 'UNDERGROUND_EMAIL_BUTTON_TEXT_COLORS'}), 5: ('wagtail.blocks.StructBlock', [[('text', 1), ('url', 2), ('background_color', 3), ('color', 4)]], {}), 6: ('underground_email.blocks.ColorBlock', (), {'default': '#cccccc', 'label': 'Color', 'palette_only': False, 'palette_setting': 'UNDERGROUND_EMAIL_HRULE_COLORS'}), 7: ('wagtail.blocks.StructBlock', [[('color', 6)]], {})}),
        ),
    ]
